name: openvoice

on:
  push:
  schedule:
    - cron: "43 */5 * * *"


jobs:
  build:
    runs-on: ubuntu-latest
    name: gandal
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
#      - uses: actions/setup-python@v2
      - name: Compile
        run:  python openvoice/commons.py

